services:
  movies:
    image: movies
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources:/data/db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/data/db/movies.db
      - RATINGS_SERVICE_URL=http://ratings:8081
    networks:
      - app-network

volumes:
  db:
    driver: local

networks:
  app-network:
    name: app-network