
services:
  movies:
    image: movies # Replace with the image name you built for your Spring Boot app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .\src\main\resources:/data/db  # Mount the database file from your host system
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/data/db/movies.db  # Location of SQLite DB inside the container
    networks:
      - mynetwork

volumes:
  db:
    driver: local

networks:
  mynetwork: 
    external: true